### ISSUE TITLE
Replace nouns / adjectives

### ISSUE THREAD

**Issue by LarsLiden** [ndaidong/txtgen#35]
Would be nice to be able to replace the nouns and adjectives rather than just add to them.  Otherwise one gets fruit and animal weighted examples

**Comment by ndaidong** [comment]
@LarsLiden thank you for your idea. Since v2.2.3, txtgen provides a few `set*` and `get*` methods for customizing sample data. Now you can get current sample set of nouns, adjectives and templates, set new samples to replace pre-defined ones, etc. Please refer README and let's me know if that helps.

**Comment by LarsLiden** [comment]
Awesome.  Thanks!
